### ISSUE TITLE
Can not change language of component

### ISSUE THREAD

**Issue by hoantran-it** [Yoctol/react-messenger-customer-chat#17]
When I change props, messenger component doesn't affect. I see in code that loadSdkAsynchronously will init something for fb. Do we have any workaround to solve this problem? Thanks!

<img width="448" alt="messenger-language" src="https://user-images.githubusercontent.com/13161875/37863633-8918da54-2f93-11e8-8db4-ccba704cd005.png">

**Comment by chentsulin** [comment]
Hi @hoantran-it, v0.6.0 should fix the issue, you can try it out.
https://github.com/Yoctol/react-messenger-customer-chat/releases/tag/v0.6.0

**Comment by hoantran-it** [comment]
Hi @chentsulin Awesome! I checked and it works perfectly. Many thanks!!!
