### ISSUE TITLE
Put the script at the end of body

### ISSUE THREAD

**Issue by hoantran-it** [Yoctol/react-messenger-customer-chat#20]
I see in code
`fjs = d.getElementsByTagName(s)[0]`;
`fjs.parentNode.insertBefore(js, fjs);`
That means we add FB script before the first script tag. However in some case the first script will be placed in **head** tag and we face this error when we try to remove the script and reload it again
![error](https://sv1.uphinhnhanh.com/images/2018/05/09/error.png)

Why don't we put FB script at the end of body. Ex: `d.body.append(js);`

Could you please to clarify it a bit. Thanks!

**Comment by xxhomey19** [comment]
Actually, those code is copied from official [quickstart docs](https://developers.facebook.com/docs/javascript/quickstart).

**Comment by hoantran-it** [comment]
@xxhomey19 Thank you! Could you please to fix it with 6.0 version which used react 15. I'm using it. Many thanks!

**Comment by chentsulin** [comment]
released as https://github.com/Yoctol/react-messenger-customer-chat/releases/tag/v0.6.1
