### ISSUE TITLE
Assign title to iframe.

### ISSUE THREAD

**Issue by kathaghera** [Yoctol/react-messenger-customer-chat#25]
Thanks for the component! It's awesome.

I was conducting an accesibility audit using lighthouse when I came across the following suggestion:
![image](https://user-images.githubusercontent.com/39765126/42146473-c891a808-7de7-11e8-8c0c-15be11dde12f.png)

Is there a way to get around this?

**Comment by tw0517tw** [comment]
Hi @kathaghera ,

This component helps loading Facebook's SDK into React. The `<iframe>` is created by Facebook's SDK, maybe you can [report an issue to their bug platform](https://developers.facebook.com/support/bugs/)?

**Comment by chentsulin** [comment]
The problem is on facebook side and nothing to do with the package.
