### ISSUE TITLE
How to hide the plugin

### ISSUE THREAD

**Issue by Rhagaer** [Yoctol/react-messenger-customer-chat#26]
![image](https://user-images.githubusercontent.com/29455240/42554379-ecc36df2-84e4-11e8-88b0-35ffae943ef3.png)

How can I hide the plugin on certain pages as described in the Facebook docs here: https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin/sdk

**Comment by xxhomey19** [comment]
Sorry for late response. It would be available after PR #23 being merged, and the default props `shouldShowDialog` will be `false`, which means it will call `FB.CustomerChat.hideDialog()` by default.

**Comment by Rhagaer** [comment]
Any idea when it might be completed :) ?

**Comment by xxhomey19** [comment]
Well, I have no idea when it'll be available sorry.

@chentsulin

**Comment by chentsulin** [comment]
Hi @Rhagaer, @xxhomey19, I just publish `0.7.0-rc.1` to npm and you can install it using following command: 

```
npm install react-messenger-customer-chat@next
```

If it works great in the next few days, I will publish `0.7.0`.

**Comment by chentsulin** [comment]
0.7.0 released.
