### ISSUE TITLE
Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by przpl** [Yoctol/react-messenger-customer-chat#30]
Error occures while processing this line:
https://github.com/Yoctol/react-messenger-customer-chat/blob/master/src/MessengerCustomerChat.js#L211

Edit: this problem occures only on localhost during development.

**Comment by przpl** [comment]
I see there is already pull request associated with this problem.

**Comment by tw0517tw** [comment]
`react-messenger-customer-chat` v0.7.1 has been released!
