### ISSUE TITLE
element.className.includes is not a function

### ISSUE THREAD

**Issue by przpl** [Yoctol/react-messenger-customer-chat#31]
Error occures in this line: https://github.com/Yoctol/react-messenger-customer-chat/blob/master/src/MessengerCustomerChat.js#L211. I am using the newest version with number 0.7.1.

**Comment by przpl** [comment]
Chrome 69 on Mac OS X

**Comment by ramadis** [comment]
I can't seem to reproduce the issue. Are you testing it in a specific website, or just the default CRA application? Do you have an SVG element in your website? 

Just trying to figure out why a DOM element is not returning a `string` when asked for the className.

**Comment by przpl** [comment]
Yes, I have SVG element on my website. This is report from sentry: https://sentry.io/share/issue/0b3ed024d4544b6aabf608043204d1dd/ I don't know yet when it happens, it happened on someone's else browser, I can't reproduce the issue also. The error occurred on Firefox and Chrome (both Windows and Mac)

**Comment by ramadis** [comment]
Do you know the browser version they were using?

**Comment by przpl** [comment]
Firefox 62 and Chrome 66, 69

**Comment by ramadis** [comment]
Oh, so no problem with those versions. I believe it is probably because of an SVG element being appended to the DOM thus triggering that function. I already created a PR that should fix the issue on those cases! Thanks for your help!

**Comment by chentsulin** [comment]
This should be fixed in 0.7.2
