### ISSUE TITLE
SDK URL Changed

### ISSUE THREAD

**Issue by Omar-Ali** [Yoctol/react-messenger-customer-chat#33]
Hello

I've been using the plugin for a couple of months, but I'm getting this warning in the console lately.

```
##########################
#   The CustomerChat plugin will soon be removed from the main Facebook SDK.
#   To continue using it please use the correct SDK URL.
#   For more details see https://fburl.com/customer-chat-sdk
##########################
```

however, the link provided redirects to facebook not found webpage.
I'm not sure if this something that I should fix from my end?

**Comment by tw0517tw** [comment]
Hi @Omar-Ali 

What version of `react-messenger-customer-chat` are you using? We've changed the SDK to new one since `v0.7.0`, please try to upgrade to newest version `v0.7.2`.

**Comment by chentsulin** [comment]
This should has been changed in 0.7.2.
