### ISSUE TITLE
Dont Works in IOS v12

### ISSUE THREAD

**Issue by pablohk** [Yoctol/react-messenger-customer-chat#35]
Hi, 
Recently there have been a IOS update to version 12 and the messenger bubble dont appear in my react view. 
I´ve installed  0.7.1,
My script:
  <script>
    (function (d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) { return; }
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.com/es_ES/messenger.Extensions.js";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'Messenger'));
  </script>

**Comment by chentsulin** [comment]
Hi @pablohk 
This component injects the `https://connect.facebook.net/${language}/sdk/xfbml.customerchat.js` script for you, so you don't need to add the script.

**Comment by chentsulin** [comment]
We didn't get any replies in a period of time, so I'm going to close this.
