### ISSUE TITLE
how to add async property for script tag, which load facebook sdk?

### ISSUE THREAD

**Issue by Sorcer23** [Yoctol/react-messenger-customer-chat#36]

**Comment by chentsulin** [comment]
@Sorcer23 
Dynamically injected scripts are asnyc by default: 

<img width="913" alt="截圖 2020-06-30 上午2 36 31" src="https://user-images.githubusercontent.com/3382565/86042950-877b4280-ba7a-11ea-9806-4ff6bf58c3d2.png">

Is there anything you want to achieve?

**Comment by chentsulin** [comment]
The script is async by default.
