### ISSUE TITLE
Support Nextjs!!?

### ISSUE THREAD

**Issue by datvtwkm** [Yoctol/react-messenger-customer-chat#37]
Does this library support Nextjs? I tried to implement but no hope!
Thank you!

**Comment by Saint2Laurent** [comment]
Did you find any workaround?

**Comment by tao** [comment]
It does work on NextJS, you can use this example: 
https://gist.github.com/tao/cde323d3652c03803b59d756279c158d

**Comment by ElegantSoft** [comment]
don't render it till you are on client side
```js
{typeof window !== "undefiend" && <MessengerComponent />}
```

**Comment by chentsulin** [comment]
See https://github.com/Yoctol/react-messenger-customer-chat#nextjsssr
