### ISSUE TITLE
Unknown prop `page_id` on <div> tag

### ISSUE THREAD

**Issue by redbaron76** [Yoctol/react-messenger-customer-chat#5]
When using this plugin, I got this in console:

```
Unknown prop `page_id` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
in div (created by MessengerCustomerChat)

Thanks

**Comment by chentsulin** [comment]
@redbaron76 Hi, we released v0.3.0 which should fix this issue on React <= 16
https://github.com/Yoctol/react-messenger-customer-chat/releases/tag/v0.3.0
