### ISSUE TITLE
iframe bubble for messeges - white bg in dark mode (tailwindcss) - how to change it?

### ISSUE THREAD

**Issue by bubuq3** [Yoctol/react-messenger-customer-chat#87]
Hello, I got a dark mode from next/themes and on dark mode on my smartphone there is a white background, but on the desktop is not shown. How to apply a color to this `iframe`? I use tailwindcss and next.js
btw. How to change colors of the divs?

![image](https://user-images.githubusercontent.com/62507500/121919628-7bde6580-cd37-11eb-8f5c-e24e47527269.png)
on mobile \/
![200967345_927177447837524_5649380595983022773_n](https://user-images.githubusercontent.com/62507500/121920031-e98a9180-cd37-11eb-8957-96a6b5261cc9.jpg)

I tried like this but dont work.:
```
@layer components {
  .cms-content > h1,
  h2 {
    @apply dark:text-gray-600;
  }
  .messenger-chat-bubble > iframe {
    @apply dark:bg-dark-posts;
  }
}
```
app.js

```
import "tailwindcss/tailwind.css";
import "../styles/globals.css";
import Footer from "../components/Footer";
import Header from "../components/Header";
import { getMDXComponent } from "mdx-bundler/client";
import MessengerCustomerChat from "react-messenger-customer-chat";

import { ThemeProvider } from "next-themes";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <ThemeProvider attribute="class">
        <Header />
        <Component {...pageProps} />

        <Footer />
        {typeof window !== "undefiend" && (
          <MessengerCustomerChat
            pageId="1xxxxx"
            appId="xxx"
            className="messenger-chat-bubble"
          />
        )}
      </ThemeProvider>
    </>
  );
}
export default MyApp;
```
edit1: Now on dark mode I got these iframe notification bubble on white and this border on white around the main bubble. What's wrong? I added `themeColor="#222222"` to `MessengerCustomerChat`
![200619910_970589787109373_1985134886635526940_n](https://user-images.githubusercontent.com/62507500/121926244-0e820300-cd3e-11eb-86fb-9488b8c276b4.jpg)

```
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer components {
  .cms-content > h1,
  h2 {
    @apply dark:text-gray-600;
  }
  .messenger-chat-bubble > iframe {
    @apply dark:bg-dark-posts;
  }
  .messenger-chat-bubble > .fb_customer_chat_icon {
    @apply dark:bg-dark-posts;
  }
}
```

**Comment by chentsulin** [comment]
As far as i can tell, `themeColor="#222222"` prop is enough in this case:

![image](https://user-images.githubusercontent.com/3382565/130347282-4210384d-26a1-4af6-89e2-6151677e27f9.png)

I don't recommend applying any css styles on iframe. You may want to remove `className` and relevant styles.
